import type { Metadata } from "next";
import { Manrope } from "next/font/google";

import ScrollCue from "./scroll-cue";
import ThemeProvider from "theme/ThemeProvider";

import PageProgress from "components/common/PageProgress";

// animate css
import "animate.css";
// import swiper css
import "swiper/css";
import "swiper/css/free-mode";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/thumbs";
// video player css
import "plyr-react/plyr.css";
// glightbox css
import "glightbox/dist/css/glightbox.css";
// custom scrollcue css
import "plugins/scrollcue/scrollCue.css";
// Bootstrap and custom scss
import "assets/scss/style.scss";
import Container from "components/Container";

import Script from "next/script";
import ReduxContainer from "components/ReduxContainer";
import { cookies } from "next/headers";
const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dongpae iceup",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const cookie = cookies()
  const cookieVaule : any = cookie.get('dissid') || '';
  return (
    <html lang="en">
      <body className={manrope.className}>
        {/* <ScrollCue> */}
        <ReduxContainer>
          <Container ssid={cookieVaule?.value}>
            <ThemeProvider>{children}</ThemeProvider>
          </Container>
        </ReduxContainer>
        {/* </ScrollCue> */}

        <PageProgress />
      </body>
    </html>
  );
}
